dist: xenial
language: python
python:
#    - "2.7"
    - "3.6"
    - "3.5"
    - "3.7"
    - "3.8"
script:
    - "gunzip tests/test_files/rf64/*.gz"
    - "python setup.py test"
#    - "py.test tests/ -v --cov wavinfo --cov-report term-missing"
before_install:
    - "sudo apt-get update"
    - "sudo add-apt-repository universe"
    - "sudo apt-get install -y ffmpeg"
    - "pip install coverage"
    - "pip install codecov"
    - "pip install pytest-cov==2.5.0"
#    - "pip install coverage==4.4"
install:
    - "pip install setuptools"
after_success:
    - "codecov"
